# Generated by Django 3.1.4 on 2021-01-29 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210129_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='criados',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='criados',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
    ]
